services:
  backend:
    build:
      context: CAMAAR_backend
      dockerfile: Dockerfile
    image: camaar_rails
    container_name: camaar_rails
    env_file:
      - .env 
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ./CAMAAR_backend:/app

networks:
  camaar:
