services:
  backend:
    build:
      context: CAMAAR_backend
      dockerfile: Dockerfile
    image: camaar_rails
    container_name: camaar_rails
    env_file:
      - .env 
    ports:
      - ${BACKEND_PORT}:3333
    volumes:
      - ./CAMAAR_backend:/app
    networks:
      - camaar
    command: bundle exec rails server -b 0.0.0.0 -p 3333

  frontend:
    build:
      context: CAMAAR_frontend
      dockerfile: Dockerfile
    image: camaar_react
    container_name: camaar_react
    env_file:
      - .env 
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./CAMAAR_frontend:/app
    networks:
      - camaar


networks:
  camaar:
