name: CI - Rails Backend

on:
  push:
    paths:
      - 'CAMAAR_backend/**'
  pull_request:
    paths:
      - 'CAMAAR_backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    defaults:
      run:
        working-directory: ./CAMAAR_backend
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Setup database
        run: |
          rails db:create
          rails db:migrate
      - name: Run tests
        run: bundle exec rspec
